SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID IN
(
  SELECT DEPARTMENT_ID FROM HR.DEPARTMENTS
  WHERE DEPARTMENT_NAME IN ('Marketing', 'Administration')
);

select FIRST_NAME, JOB_ID,
DECODE(JOB_ID,
       'IT_PROG','PROGRAMADOR',
       'FI_ACCOUNT', 'CONTADOR',
       'VERIFICAR') CARGO
from HR.EMPLOYEES;

SELECT FIRST_NAME, JOB_ID, SALARY,
	CASE
    	WHEN SALARY < 5000 THEN 'AUMENTO'
        WHEN SALARY > 10000 THEN 'VERIFICAR'
        ELSE 'NÃO AUMENTAR'
    END VERIFICAR_AUMENTO
FROM HR.EMPLOYEES;